imports:
  - datetime
  - random
data:
  - sources:
      - i1:m1:s1
      - i2:m2:s1
      - i3:m2:s2
      - i4:m1:s1
  - average_amount: 10
  - actions:
      - auth
      - capture
      - refund
  - errors:
      - database failure
      - processor failure
      - invalid payment
      - ''
output:
  transmitters: 2
  mean_wait: 2
  class: transgenset.output.AMQPTransmitter
  parameters:
    hostname: localhost
    port: 5672
    userid: guest
    password: guest
    virtual_host: ''
    exchange: transactions
#   class: transgenset.output.FileTransmitter
#   parameters:
    
